[build]
  # base = "project/"
  # publish = "build-output/"
  # command = "echo 'default context'"
[context.writeups]
  publish = "book/"
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.11/mdbook-v0.4.11-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
